### ISSUE TITLE
Console error... I Need help :'(

### ISSUE THREAD

**Issue by XDan000** [PEXPlugins/PermissionsEx#1890]
Prefixes doesn't work Spigot 1.8

This is the error pls help me :'(

Full error:
java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(I)Lcom/google/common/cache/CacheBuilder;
	at ru.tehkode.permissions.RegExpMatcher.<init>(RegExpMatcher.java:17)
	at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:58)
	at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:164)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:333)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:352)
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:313)
	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:400)
	at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:368)
	at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:323)
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211)
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:496)
	at java.lang.Thread.run(Unknown Source)

**Comment by CullanP** [comment]
Prefixes work on spigot 1.8, update to the latest pex.

**Comment by Stormbow** [comment]
I believe this is the (very old) "Guava needs to be updated" error.

**Comment by XDan000** [comment]
Sorry I do shit in the config file xD I remove default option :p now it
works correctly thanks!
Em 14/02/2015 09:34, "Stormbow" <notifications@github.com> escreveu:

**Comment by Stormbow** [comment]
Excellent.  :)
